var listening_array = [
	["（一）我学习汉语"],
	["麦克", "请问，你贵姓？", "Qǐngwèn, nǐ guìxìng?", "Xin hỏi, quý danh của bạn là gì?"],
	["张东", "我姓张。", "Wǒ xìng zhāng.", "Tôi họ Trương"],
	["麦克", "你叫什么名字？", "Nǐ jiào shénme míngzì?", "Bạn tên gì?"],
	["张东", "我叫张东。", "Wǒ jiào zhāng dōng.", "Tôi tên Trương Đông"],
	["麦克", "你是哪国人？", "Nǐ shì nǎ guórén?", "Bạn là người nước nào?"],
	["张东", "我是中国人。你是哪国人？", "Wǒ shì zhōngguórén. Nǐ shì nǎ guó rén?", "Tôi là người Trung Quốc. Bạn là người nước nào?"],
	["麦克", "我是美国人。", "Wǒ shì měiguó rén.", "Tôi là người Mỹ."],
	["张东", "你学习什么？", "Nǐ xuéxí shénme?", "Bạn học gì?"],
	["麦克", "我学习汉语。", "Wǒ xuéxí hànyǔ.", "Tôi học tiếng Hán."],
	["张东", "汉语难吗？", "Hànyǔ nán ma?", "Tiếng Hán khó không?"],
	["麦克", "汉字很难，发音不太难。", "Hànzì hěn nán, fāyīn bù tài nán.", "Chữ Hán rất khó, phát âm không khó lắm"],
	["（二）这是什么书"],
	["A", "这是什么？", "Zhè shì shénme?", "Đây là gì?"],
	["B", "这是书。", "Zhè shì shū.", "Đây là sách."],
	["A", "这是什么书？", "Zhè shì shénme shū?", "Đây là sách gì?"],
	["B", "这是中文书。", "Zhè shì zhōngwén shū.", "Đây là sách Hán Ngữ."],
	["A", "这是谁的书？", "Zhè shì shéi de shū?", "Đây là sách của ai?"],
	["B", "这是老师的书。", "Zhè shì lǎoshī de shū.", "Đây là của giáo viên."],
	["A", "那是什么？", "Nà shì shénme?", "Đó là gì?"],
	["B", "那是杂志。", "Nà shì zázhì.", "Đó là tạp chí."],
	["A", "那是什么杂志？", "Nà shì shénme zázhì?", "Đó là tạp chí gì?"],
	["B", "那是英文杂志。", "Nà shì yīngwén zázhì.", "Đó là tạp chí tiếng Anh."],
	["A", "那是谁的杂志？", "Nà shì shéi de zázhì?", "Đó là tạp chí của ai?"],
	["B", "那是我朋友的杂志。", "Nà shì wǒ péngyǒu de zázhì.", "Đó là tạp chí của bạn tôi."]
];

var vocabulary_array = [
	['1.', '请问', '动', 'qǐngwèn', 'xin hỏi'],
    ['', '问', '动', 'wèn', 'hỏi, tìm hiểu'],
    ['2.', '贵姓', '名', 'guìxìng', 'quý danh'],
    ['3.', '姓', '动, 名', 'xìng', 'họ'],
    ['4.', '叫', '动', 'jiào', 'gọi, tên là'],
    ['5.', '名字', '名', 'míngzì', 'tên'],
    ['6.', '哪', '代', 'nǎ', 'nào'],
    ['7.', '国', '名', 'guó', 'quốc gia'],
    ['', '中国', '名', 'zhōngguó', 'Trung Quốc'],
    ['', '德国', '名', 'déguó', 'nước Đức'],
    ['', '俄国', '名', 'éguó', 'nước Nga'],
    ['', '法国', '名', 'fǎguó', 'nước Pháp'],
    ['', '韩国', '名', 'hánguó', 'Hàn Quốc'],
    ['', '美国', '名', 'měiguó', 'nước Mỹ'],
    ['', '日本 (国)', '名', 'rìběn (guó)', 'nước Nhật'],
    ['', '英国', '名', 'yīngguó', 'nước Anh'],
    ['8.', '人', '名', 'rén', 'người'],
    ['9.', '学习', '动', 'xuéxí', 'học'],
    ['10.', '汉字', '名', 'hànzì', 'chữ Hán'],
    ['11.', '发音', '名, 动', 'fāyīn', 'phát âm'],
    ['12.', '什么', '代', 'shénme', 'cái gì'],
    ['13.', '书', '名', 'shū', 'sách'],
    ['14.', '谁', '代', 'shéi', 'ai'],
    ['15.', '的', '助', 'de', 'của ...'],
    ['16.', '那', '代', 'nà', 'đó, đấy, kia ...'],
    ['17.', '杂志', '名', 'zázhì', 'tạp chí'],
    ['18.', '文', '名', 'wén', 'tiếng (ngôn ngữ)'],
    ['', '中文', '名', 'zhōngwén', 'tiếng Hoa'],
    ['', '阿拉伯文', '名', 'ālābó wén', 'tiếng Ả Rập'],
    ['', '德文', '名', 'dé wén', 'tiếng Đức'],
    ['', '俄文', '名', 'é wén', 'tiếng Nga'],
    ['', '法文', '名', 'fǎwén', 'tiếng Pháp'],
    ['', '韩文', '名', 'hánwén', 'tiếng Hàn'],
    ['', '日文', '名', 'rìwén', 'tiếng Nhật'],
    ['', '西班牙文', '名', 'xībānyá wén', 'tiếng Tây Ban Nha'],
    ['', '英文', '名', 'yīngwén', 'tiếng Anh'],
    ['19.', '朋友', '名', 'péngyǒu', 'bạn bè']
];

var name_array = [
	["麦克", "màikè", "Mike"],
	["张东", "zhāng dōng", "Trương Đông"]
];
