var listening_array = [
	["（ 买水果 ）"],
	["A", "你买什么？", "Nǐ mǎi shénme?", "Bạn mua gì?"],
	["B", "我买水果。苹果一斤多少钱？", "Wǒ mǎi shuǐguǒ. Píngguǒ yī jīn duōshǎo qián?", "Tôi mua trái cây. Một cân táo bao nhiêu tiền?"],
	["A", "三块。", "Sān kuài.", "Ba đồng."],
	["B", "三块？太贵了。两块五吧。", "Sān kuài? Tài guìle. Liǎng kuài wǔ ba.", "Ba đồng? Hơi đắt rồi. Hai đồng năm nhé."],
	["A", "你要几斤？", "Nǐ yào jǐ jīn?", "Bạn muốn mấy cân?"],
	["B", "我买五斤。", "Wǒ mǎi wǔ jīn.", "Tôi mua năm cân."],
	["A", "还要别的吗？", "Hái yào bié de ma?", "Còn muốn cái khác không?"],
	["B", "橘子怎么卖？", "Júzi zěnme mài?", "Quýt bán thế nào?"],
	["A", "两块。", "Liǎng kuài.", "Hai đồng."],
	["B", "要两斤。一共多少钱？", "Yào liǎng jīn. Yīgòng duōshǎo qián?", "Muốn hai cân. Tổng cộng bao nhiêu tiền?"],
	["A", "一共十六块五（毛）。你给十六块吧。", "Yīgòng shíliù kuài wǔ (máo). Nǐ gěi shíliù kuài ba.", "tổng cộng mười sáu đồng năm. Bạn đưa mười sáu nhé."],
	["B", "给你钱。", "Gěi nǐ qián.", "Gửi bạn tiền"],
	["A", "这是五十，找您三十四块。", "Zhè shì wǔshí, zhǎo nín sānshísì kuài.", "Đây là năm mươi. Trả ngài ba mươi tư đồng."]
];

var vocabulary_array = [
	['1.', '买', '动', 'mǎi', 'mua'],
    ['2.', '水果', '名', 'shuǐguǒ',	'hoa quả'],
    ['3.', '苹果', '名', 'píngguǒ', 'quả táo'],
    ['4.', '斤', '量', 'jīn', 'cân (đơn vị đo)'],
    ['', '公斤', '量', 'gōngjīn', 'kilogram'],
    ['5.', '贵', '形', 'guì', 'đắt tiền'],
    ['6.', '了', '助', 'le', 'trợ từ ngữ khí khẳng định'],
    ['7.', '吧', '助', 'ba', 'trợ từ ngữ khí yêu cầu, thương lượng.'],
    ['8.', '多少', '代', 'duōshǎo', 'bao nhiêu'],
    ['', '多', '形', 'duō', 'nhiều'],
    ['', '少', '形', 'shǎo', 'ít'],
    ['9.', '块（元）', '量', 'kuài (yuán)', 'đồng (đơn vị tiền Trung Quốc)'],
    ['', '角（毛）', '量', 'jiǎo (máo)', 'hào (1/10 của 1 đồng)'],
    ['', '分', '量', 'fēn', 'xu (1/10 của 1 hào)'],
    ['10.', '还', '副', 'hái', 'còn, vẫn còn'],
    ['11.', '别的', '代', 'bié de', 'khác, cái khác'],
    ['12.', '橘子', '名', 'júzi', 'quả quýt'],
    ['13.',	'怎么',	'代', 'zěnme', 'thế nào'],
    ['14.',	'卖', '动', 'mài', 'bán'],
    ['15.',	'两', '数', 'liǎng', 'hai'],
    ['16.',	'一共',	'副', 'yīgòng', 'tổng cộng'],
    ['17.', '給', '动', 'gěi', 'đưa, cho'],
    ['18.', '找', '动', 'zhǎo', 'tìm, trả lại (tiền thừa)']
];
