var listening_array = [
	["（一）这个黑箱子很重"],
	["（在机场）"],
	["A", "你没有箱子吗？", "Nǐ méiyǒu xiāngzi ma?"],
	["B", "有啊。我的在这儿呢。", "Yǒu a. Wǒ de zài zhè'er ne."],
	["A", "我的很重，你的重不重？", "Wǒ de hěn zhòng, nǐ de zhòng bù chóng?"],
	["B", "这个黑的很重，那个红的比较轻。", "Zhège hēi de hěn zhòng, nàgè hóng de bǐjiào qīng."],
	["A", "你的箱子很新，我的很旧。", "Nǐ de xiāngzi hěn xīn, wǒ de hěn jiù."],
	["B", "那个新的是朋友的。这个旧的是我的。", "Nàgè xīn de shì péngyǒu de. Zhège jiù de shì wǒ de."],
	["（二）这是不是中药"],
	["（在海关）"],
	["A", "先生，这些黑的是什么东西？", "Xiānshēng, zhèxiē hēi de shì shénme dōngxī?"],
	["B", "这是一些药。", "Zhè shì yīxiē yào."],
	["A", "什么药？", "Shénme yào?"],
	["B", "中药。", "Zhōngyào."],
	["A", "这是不是药？", "Zhè shì bùshì yào?"],
	["B", "这不是药，这是茶叶。", "Zhè bùshì yào, zhè shì cháyè."],
	["A", "那个箱子里是什么？", "Nàgè xiāngzi lǐ shì shénme?"],
	["B", "都是日用品。有两件衣服，一把雨伞和一瓶香水，还有一本书，一本词典，两张光盘和三只笔。", "Dōu shì rìyòngpǐn. Yǒu liǎng jiàn yīfú, yī bǎ yǔsǎn hé yī píng xiāngshuǐ, hái yǒuyī běn shū, yī běn cídiǎn, liǎng zhāng guāngpán hé sān zhī bǐ."]
];

var vocabulary_array = [
	['1.', '没（有）', '动, 副', 'méi (yǒu)', 'không có, chưa có'],
    ['2.', '箱子', '名', 'xiāngzi', 'cái hòm, vali, rương'],
    ['3.', '有', '动', 'yǒu', 'có'],
    ['4.', '这儿', '代', 'zhè\'er', 'đây, ở đây'],
    ['5.', '重', '形', 'zhòng', 'nặng'],
    ['6.', '黑', '形', 'hēi', 'màu đen'],
    ['7.', '红', '形', 'hóng', 'màu đỏ'],
    ['8.', '轻', '形', 'qīng', 'nhẹ'],
    ['9.', '旧', '形', 'jiù', 'cũ'],
    ['10.', '药', '名', 'yào', 'thuốc'],
    ['', '中药', '名', 'zhōngyào', 'thuốc bắc, thuốc đông y'],
    ['', '西药', '名', 'xīyào', 'thuốc tây'],
    ['11.', '茶叶', '名', 'cháyè', 'lá trà'],
    ['12.', '里', '名', 'lǐ', 'trong, bên trong'],
    ['13.', '日用品', '名', 'rìyòngpǐn', 'đồ dùng hàng ngày'],
    ['14.', '件', '量', 'jiàn', 'cái, chiếc (đồ dạng khối kiện)'],
    ['15.', '衣服', '名', 'yīfú', 'quần áo'],
    ['16.', '把', '量', 'bǎ', 'chiếc, cái (đồ có tay cầm)'],
    ['17.', '雨伞', '名', 'yǔsǎn', 'cái ô, cái dù'],
    ['', '雨', '名', 'yǔ', 'mưa'],
    ['18.', '瓶', '名, 量', 'píng', 'chai, lọ'],
    ['19.', '香水', '名', 'xiāngshuǐ', 'nước hoa'],
    ['', '水', '名', 'shuǐ', 'nước'],
    ['20.', '本', '量', 'běn', 'quyển, cuốn'],
    ['21.', '词典', '名', 'cídiǎn', 'từ điển'],
    ['22.', '张', '量', 'zhāng', 'miếng, tờ (giấy ...)'],
    ['23.', '光盘', '名', 'guāngpán', 'đĩa CV, DVD'],
    ['24.', '支', '量', 'zhī', 'cái (bút)'],
    ['25.', '笔', '名', 'bǐ', 'bút']
];
